feat: Create models
wecode-bootcamp-korea/32-2nd-WeEats-backend pull request #1
Opened 2022-05-10 09:04 UTC by celeste-6

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
![image](https://user-images.githubusercontent.com/96307607/167587560-b010425b-2a7d-4859-9656-92c0c24bea45.png)
- App: core, restaurants, reviews, users, reservations 에 대한 models.py 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- Product, Review, Reservation 중심의 모델링 구현
- Users
  - 카카오 sns 로그인을 통해 가져올 수 있는 PK 값을 위한 Big Integer Field를 구현
- Restaurants
  - 기본 정보: 이름, 식당 카테고리, 주소, 위도&경도
  - 위도와 경도같은 경우 Decimal Field로 구현하여 추후 지도에 사용
  - 자주 바뀔 수 있는 thumbnail_image 같은 경우 접근성이 용이하도록 one-to-one 테이블 및 필드 구현
- Reviews
  - user, restaurant 정보를 FK로 가져옴
  - review에 사용할 이미지 테이블을 생성하여 한 리뷰에 여러개의 이미지를 첨부 가능하도록 **review_image 테이블에 review FK 추가**
- Reservations
  - restaurant, user, status를 FK로 가져옴
  - start_time, end_time, date를 사용해서 예약 날짜와 시간을 지정
  - visitor_count를 사용해서 해당 식당에 몇명의 인원수가 예약했는지 기록

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- thumbnail_image 자주 바뀌거나 사용할것같은 테이블은 따로 만들어 데이터베이스 접근성을 용이하게 만드는것을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- review당 review_image가 필수는 아니라고 null=True를 넣어주고 싶은데, 테이블을 따로 지정하여서 굳이 지정해줘야할 필요가 있는지 궁금합니다.

2022-05-10 09:18 UTC, kyeongraekim requested changes

2022-05-10 09:18 UTC, kyeongraekim commented on restaurants/models.py
> +class Restaurant_Image(TimeStampedModel):
created_at, updated_at이 필요 없는 테이블의 경우에는 TimeStampedModel을 사용하실 필요가 없으실 것 같아요~

2022-05-10 09:18 UTC, kyeongraekim commented on restaurants/models.py
> +class Restaurant_Image(TimeStampedModel):
전체 모델 다시 한 번 훑어주시고 TimeStampModel을 뺄 곳, 넣을 곳을 다시 한번 고려해주세요~

2022-05-10 09:18 UTC, kyeongraekim commented on reviews/models.py
> +    content    = models.TextField(null=True)
CharField, TextField는 빈칸을 두어야 할 떄 null 보다는 blank=True가 더 적합합니다. 관련 이유를 한 번 찾아서 코멘트로 남겨주세요!~

2022-05-10 09:18 UTC, kyeongraekim commented on reviews/models.py
> +    url    = models.CharField(max_length=500)
url 필드는 최대 길이를 넉넉히 1000자 정도는 잡아주세요~

2022-05-10 09:18 UTC, kyeongraekim commented on users/models.py
> +    kakao_login = models.BigIntegerField(max_length=50)
kakao_id 정도의 필드값이 더 적합할 것 같습니다~

2022-05-10 09:18 UTC, kyeongraekim commented on reservations/models.py
> +    visitor_count = models.IntegerField(max_length=50)
0또는 양의 정수로 표현 가능한 부분이니 PositiveIntegerField 혹은 PositiveSmallIntegerField 사용을 고려해보세요~ 그리고 integer field는 max_length 설정이 불가할 것 같은데 한 번 확인해주세요~

2022-05-10 09:18 UTC, kyeongraekim commented on reservations/models.py
> +    status        = models.ForeignKey('ReservationStatus', on_delete=models.CASCADE, default=1)
혹시 디폴트로 설정한 1번 id에 대한 상태 내역은 무엇인지 댓글로 알려주실 수 있나요?

2022-05-11 00:31 UTC, celeste-6 commented on reservations/models.py
> +    status        = models.ForeignKey('ReservationStatus', on_delete=models.CASCADE, default=1)
예약 접수 상태가 되는것을 자동으로 설정하고 싶어서 그러한 상태를 default 값 status id=1로 저장할 예정이었습니다.

2022-05-11 01:49 UTC, celeste-6 commented on reviews/models.py
> +    content    = models.TextField(null=True)
해당 필드를 필수로 만들지 않으려고 할때 null=True 보다는 blank=True를 사용하여 DB에서는 빈 값이 빈 문자열(‘’)로 설정됨으로써 null과 빈 값을 빈 문자열으로만 판단할 수 있게 된다는 장점을 가질 수 있다고 하네요. 앞으로는 CharField, TextField에 blank=True로 사용하는 연습을 하겠습니다!

2022-05-11 02:02 UTC, celeste-6 commented on restaurants/models.py
> +class Restaurant_Image(TimeStampedModel):
전체적으로 검토 하였습니다!

2022-05-11 02:03 UTC, celeste-6 commented on reservations/models.py
> +    visitor_count = models.IntegerField(max_length=50)
넵 확인하여 수정하였습니다!

2022-05-11 03:13 UTC, kyeongraekim commented on reservations/models.py
> +    status        = models.ForeignKey('ReservationStatus', on_delete=models.CASCADE, default=1)
해당 디폴트 내용은 비즈니스 로직(View) 선에서 해결할 수 있게 변경해보는 것은 어떨까요? 
모델 선에서 디폴트 값을 정하는 것은 충분히 가능성 있는 기획일 수 있겠으나, 숫자 1로 하드 코딩 되어있다는 점과 추후 db 기획상 변동 내역이 생길 때 마다 migration을 새롭게 해야 될 것이라는 점이 걸리네요. 
추후 enum class를 적극적으로 활용하도록 멘토링 방향성을 잡아드릴 예정인데 해당 내용도 디폴트값 제거 요인으로 고려할 수 있겠습니다.

2022-05-11 04:56 UTC, celeste-6 commented on reservations/models.py
> +    status        = models.ForeignKey('ReservationStatus', on_delete=models.CASCADE, default=1)
네 이해하였습니다 수정하였고 추후 view 작성시 고려하겠습니다 감사합니다!

2022-05-11 05:52 UTC, kyeongraekim approved these changes
LGTM!~

2022-05-11 05:52 UTC, merged