feat: create restaurantview get
wecode-bootcamp-korea/32-2nd-WeEats-backend pull request #8
Opened 2022-05-17 11:18 UTC by celeste-6

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 식당 리스트 구현
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- query parameter로 offset, limit, category_id, order 전달 받기
- order의 값이 Random일시, 식당리스트를 랜덤 순서로 돌려줌
- 카테고리 아이디 지정시 그 해당 카테고리의 식당리스트를 돌려줌
- 모든 식당 리스트 지정시 페이지네이션 구현
- 식당 상세내용: id, name, address, open_time, close_time, latitude, longitude, detail_image 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-05-18 02:37 UTC, kyeongraekim requested changes

2022-05-18 02:37 UTC, kyeongraekim commented on restaurants/tests.py
> +    def test_main_view_get_method(self):
테스트 함수명에는 success or fail에 대한 내용이 명시가 되면 좋습니다~ 그리고 ux적인 측면에서 정확히 어떠한 기능을 사용할 때 성공/실패를 의도해주셨는지 작성해주실 필요가 있습니다. 
아래의 예시를 참고하여서 전체적으로 반영해주세요~
```
test_success_get_restaurant_data_in_random_order 
test_fail_get_restaruant_data_without_offset_and_limit_values

2022-05-18 02:37 UTC, kyeongraekim commented on restaurants/tests.py
> +    def tearDown(self):
teardown의 위치는 굳이 가장 마지막에 올 필요가 없습니다. 해당 함수내에서 어쩌피 마지막에 동작할 함수임으로 setup 함수 아래로 위치해주셔서 다른 개발자들에게 teardown 기능을 놓치지 않았음을 확실히 보여주세요~

2022-05-18 02:37 UTC, kyeongraekim commented on we_eats/urls.py
> +    # path('reservations', include('reservations.urls')),
깃헙에 푸시하는 모든 소스코드는 상용화 목적 품고 있습니다. 따라서 불필요한 주석, 의도치 않은 코드는 꼭 두번 세번 검토해주신 후 올려주세요~

2022-05-18 11:43 UTC, kyeongraekim requested changes

2022-05-18 11:43 UTC, kyeongraekim commented on restaurants/tests.py
> +    # Fail to be added - test_fail_get_restaurant_data_without_offset_and_limit_values
이부분은 아직 처리중이신걸까요?

2022-05-18 11:54 UTC, celeste-6 commented on restaurants/tests.py
> +    # Fail to be added - test_fail_get_restaurant_data_without_offset_and_limit_values
exception 처리 하려고 리마인더 겸 넣었는데 일단 빼고 다시 푸쉬 했습니다~!

2022-05-19 05:21 UTC, kyeongraekim approved these changes
LGTM!~ 잡아드린 방향성대로 validation 내용을 잘 반영해주셨네요~

2022-05-19 05:21 UTC, merged